# Bot-Token -> Token de seu Bot
# Observação: O plugin não irá atrapalhar o funcionamento do Bot
Bot-Token: "bot-token"

# Bot-Prefix -> Prefixo que o seu Bot utiliza
Bot-Prefix: "/"

# Guild-ID -> Coloque o ID de seu servidor no Discord
Guild-ID: "guild-id"

# BungeeCord -> O plugin desativará funções que serão substituídos pelo plugin BungeeCord
# Recomendação: true (Caso não utilize BungeeCord mantenha 'false')
BungeeCord: false

# Use-MySQL -> O plugin utilizará o banco de dados MySQL
# Observação: Se a opção for 'false' será usado arquivos internos e BungeeCord será desabilitado
Use-MySQL: false
MySQL:
  Host: 'localhost'
  User: 'root'
  Port: 3306
  Password: ''
  Database: 'database'

# Join-Warn -> Sempre que um jogador não vinculado entrar neste servidor, será notificado que a sua conta não foi vinculada
# Recomendação: true
Join-Warn: true

Options:
  change_names: true
  Format:

# Sync-Chat -> As mensagens dos jogadores neste servidor serão enviadas para um canal no discord
# Recomendação: true (Se necessário, crie canais separados por servidores)
Sync-Chat: false
# Prefixos disponíveis:
# %date% -> Data (01/01/2001)
# %hours% -> Horas (00:00:00)
# %player% -> Nickname (wypixel)
# %message% -> Mensagem ("Olá, bom dia!")
Chat:
  # Channel-ID -> ID do Canal
  channel-ID: ""
  # Format -> Formato de como sairá a mensagem.
  format: "[SKYWARS] **%hours%** %player%: %message%"